name: Application tests

on:
  pull_request:
    branches:
      - main
  workflow_call:

jobs:
  tests:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    services:
      postgres:
        image: postgres:latest
        ports:
          - 5432:5432
        env:
          POSTGRES_DB: zupa_test
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
        options: --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      NODE_ENV: test
      RAILS_ENV: test
      DATABASE_URL: "postgres://postgres:password@localhost:5432/zupa_test"
    steps:
      - uses: actions/checkout@v4

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1.7
          bundler-cache: true

      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: yarn

      - name: Install JS dependencies and build assets
        run: |
          yarn install
          yarn build

      - name: Setup database
        run: |
          cp .env.sample .env
          cp .env.test.sample .env.test
          bin/rails db:schema:load --trace

      - name: Run RSpec tests
        env:
          GOOGLE_DRIVE_CLIENT_ID: dummy
          GOOGLE_DRIVE_CLIENT_CERT_URL: dummy
          GOOGLE_DRIVE_PROJECT_ID: dummy
          GOOGLE_DRIVE_PRIVATE_KEY_ID: dummy
          GOOGLE_DRIVE_PRIVATE_KEY: ${{ secrets.DUMMY_GOOGLE_PRIVATE_KEY }} # in GitHub secrets (Settings -> Secrets and variables -> Actions -> Repository secrets)
          GOOGLE_DRIVE_CLIENT_EMAIL: dummy

        run: |
          bundle exec rspec

      - name: Run JavaScript tests
        run: |
          yarn test
